### PR TITLE
3D plots now available?

### PR DESCRIPTION
**Pull request by PallHaraldsson**
I haven't take a close look, maybe all the 3D plot stuff is immature, not as good/complete as in MATLAB or something you are trying to compare too, but at least something seems to be available:

https://plot.ly/julia/3d-surface-plots/

[I also wander, since you can call MATLAB, can you use their plot features? Or probably MATLAB would need to be the main language. That should work if calling in the other direction(?), I haven't promoted that as I believe it may be immature, and maybe even from Julia-->MATLAB..?]

### CODE REVIEW

**Comment by stevengj** [comment]
@PallHaraldsson, there are 3d plots in a variety of Julia packages.  PyPlot has some 3d plots, and it is also possible to call e.g. MayaVi via PyCall for even more 3d plots.  There is also GLPlot (https://github.com/SimonDanisch/GLPlot.jl), and maybe others.

**Comment by timholy** [comment]
Note this is a PR to delete the "3D plots" from the documentation. Did you mean to close without merging?

**Comment by PallHaraldsson** [comment]
"PR to delete", right, thanks, that was the main point, and I just squeezed in some questions.. You confirmed what I thought, that 3D plots are available (and if they are not immature implementations) then the README is just wrong and unhelpful to the reader.

I have trouble as it is convincing [MATLAB] friends to use Julia and possibly these MATLAB packages..

**Comment by stevengj** [comment]
Oh, sorry, I missed that.

**Comment by timholy** [comment]
No worries, managing the flow is near-impossible.

**Pull request merged**
